REV-103/회원가입 페이지 구현
prgrms-web-devcourse/Team-12-ReviewRanger-FE pull request #30
Opened 2023-11-04 08:07 UTC by hayamaster

## 📑 구현 내용 

- [x] 회원가입 페이지 기능과 디자인 구현
- [x] 이메일, 이름, 비밀번호 유효성 검사를 위한 `authValidation` util 함수 구현
- [x] Input 공통 컴포넌트 구현
- [x] 리뷰레인저 로고 아이콘 추가 

- 모바일
<img width="270" alt="image" src="https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-FE/assets/88622675/52a00f6c-234a-4cc6-a577-95197f0ff025">

<img width="270" alt="image" src="https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-FE/assets/88622675/6cbf7d50-58e1-425d-b61b-acfb4fd6a509">

<br/>
<br/>

- 웹
<img width="400" alt="image" src="https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-FE/assets/88622675/6da64437-10ea-4e8a-8cc2-43663d2678be">

<img width="400" alt="image" src="https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-FE/assets/88622675/6d92ae88-6dcd-4670-9c51-5d9782965cca">

<br/>

## 🚧 참고 사항

1. Input 컴포넌트 구현 및 PasswordInput 컴포넌트 삭제
  - 회원가입에는 이메일, 이름, 비번, 비번확인 총 4개 input이 존재하여 각 컴포넌트를 만들기보다 하나의 `Input` 컴포넌트를 구현하고, type을 prop으로 받아 구분하였습니다.

2. 반응형은 웹 min-width의 기준을 [tailwind 공식문서](https://tailwindcss.com/docs/screens) 기준 `lg:`로 하였습니다. (lg는 width=1024px)입니다.

3. 이메일, 이름, 비밀번호 유효성 검사
  - 이메일 형식: `영어 또는 숫자 + @ + 영어 + . + 영어`
  - 이름 형식: `숫자 또는 문자 또는 '[' 또는 ']' 또는 '-', 3글자 이상 12글자 이하`
  - 비밀번호 형식: `영어와 숫자를 하나 이상 포함하여 5글자 이상 15글자 이하`

4. 이메일, 이름, 비밀번호의 유효성 검사와 input 이벤트 처리는 각 Hook으로 만들어 관리했습니다. 

5. 회원가입 버튼 클릭 시, 이메일의 중복 검사와 이름의 중복 검사가 일어나고 모두 통과되면 회원가입이 성공적으로 이루어 집니다. 회원가입에 성공하면 로그인 페이지로 이동합니다.
  - 회원가입 버튼 -> 이메일 중복 검사 -> 이름 중복 검사 -> 회원가입 완료 -> 로그인 페이지 이동

6. 회원가입 이벤트 또한 Hook을 만들어 관리했습니다. 각 input의 `-FailMsg`를 props로 받는데, 이는 모든 input의 유효성 검사 통과여부를 확인하기 위함입니다.
```typescript
const { handleSignUpButtonClick } = useSignUpCheck({
    email,
    emailFailMsg,
    setEmailFailMsg,
    nameFailMsg,
    setNameFailMsg,
    name,
    password,
    passwordFailMsg,
    passwordConfirmFailMsg,
  })
```

<br/>

## ❓ 궁금한 점

- 일단 효리님께서 말씀해주신대로 input에서 focus를 잃을 때, 해당 input의 대해 유효성 검사를 진행해주었습니다. 근데 input에 글을 입력할 때마다 검사해서 보여주는 것도 UX적으로 더욱 편리할 것 같다는 생각이 듭니다...! 유효성 검사가 서버와 통신하는 것이 아니라서 성능에 부담이 없을 것 같다는 개인적 의견입니다...! 다른 분들은 어떻게 생각하시나요??

2023-11-04 10:27 UTC, hayamaster commented on src/pages/SignUpPage/hooks/useSignUpCheck.ts
> +                      signUp(
아 .. 제가 콜백 지옥을 만들어버렸네요. 이건 mutateAsync를 쓰면 해결할수 있습니다. 수정해볼게용

2023-11-04 16:07 UTC, hyoribogo requested changes
코멘트로 다 달아놓고 내일 회의 때 더 자세하게 설명 드리겠습니다!!

- 데스크탑 텍스트 크기 변경 안 되어 있네요!
- svg는 정사각형 프레임의 svg를 가져와 주세요!
- 이미지는 images 폴더면 좋겠어요!!
- 복잡한 일러스트는 png로 가져오면 좋을 것 같습니다.
- 로고는 제가 넣어둘게용 !!! :)
- msg는 줄임말입니다.
- 주하님 말씀대로 입력할 때마다 유효성 검증해주는게 좋을 것 같아요 !!
- '유효한 이메일 주소가 아니야!' 같은 건 상수로 처리해주면 더 좋을 것 같습니다!

2023-11-04 16:21 UTC, khj0426 approved these changes
고생하셨습니다..!!.!! 커밋 하신 걸 보면 진짜진짜 ... 👍 👍

2023-11-04 16:21 UTC, khj0426 commented on src/components/Input/index.tsx
> +interface InputProps {
`Input`컴포넌트는 되게 다양하게 쓰일 거 같아요! 만들어주신 주하님 감사드려요! 잘 쓰겠습니다 💯 👍 

기본적인 다양한 input의 props도 사용하고 싶다면 아래와 같이 타입을 적어줄 수도 있을 것 같아요!!
이렇게 하면 지금의 InputProps뿐만 아니라 다른 input의 props도 받을 수 있게 되서 더 범용성있을 것 같아요!

<input> 태그의 모든 props를 지원하면서도 추가적으로 inputRef, handleInputChange, handleInputBlur, type, msg 등의 속성을 가질 수 있는 Input 컴포넌트를 만들 수 있게 할 수 있습니다!

```ts
interface InputProps
  extends Omit<ComponentPropsWithoutRef<'input'>, 'disabled'> {
  inputRef?: RefObject<HTMLInputElement>
  handleInputChange?: (e: ChangeEvent<HTMLInputElement>) => void
  handleInputBlur?: (e: FocusEvent<HTMLInputElement>) => void
  disabled?: boolean
  type: keyof typeof INPUT_TYPE
  msg?: string
}

```

2023-11-04 16:21 UTC, khj0426 commented on src/pages/SignUpPage/hooks/useNameCheck.ts
> +    if (nameRef.current !== document.activeElement) {
요건 따로 유틸로도  분리 할 수도 있을 거 같아요! 많은 곳에서 사용하고 있는 것 같아서요!!

2023-11-04 16:21 UTC, khj0426 commented on src/utils/authValidation.ts
> +const EMAIL_REGEXP = /[a-z0-9]+@[a-z]+\.[a-z]{2,8}$/
요 상수들을 분리 안하신 이유가 궁금해요.!.!.!

2023-11-05 19:26 UTC, hayamaster commented on src/components/Input/index.tsx
> +interface InputProps {
오 그렇군요! 감사합니다! 수정하겠습니다!

2023-11-05 19:28 UTC, hayamaster commented on src/pages/SignUpPage/hooks/useNameCheck.ts
> +    if (nameRef.current !== document.activeElement) {
유효성 검사 시점을 변경하면서 필요없어졌습니다! ㅎㅎ

2023-11-05 19:28 UTC, hayamaster commented on src/utils/authValidation.ts
> +const EMAIL_REGEXP = /[a-z0-9]+@[a-z]+\.[a-z]{2,8}$/
헉 분리하겠습니다!!!

2023-11-05 19:47 UTC, hyoribogo approved these changes
주하님 확인했습니다!!!!!!!

2023-11-05 19:47 UTC, hyoribogo commented on src/assets/icons/logo-col.svg
👍🏻

2023-11-05 19:47 UTC, hyoribogo commented on src/assets/images/ranger-head.png
ㅋㅋㅋㅋ헤드

2023-11-05 19:47 UTC, hyoribogo commented on src/pages/SignUpPage/hooks/useSignUpCheck.ts
> +  const { mutateAsync: checkDuplicatedName } = useCheckDuplicatedName()
이렇게 작성하면 어떻게 동작하나요?!

2023-11-05 19:47 UTC, hyoribogo commented on src/utils/constants.ts
> +  PASSWORD_REGEXP: /^(?=.*[a-zA-Z])(?=.*[0-9]).{5,15}$/,
혹시 5~15자로 받은 이유가 있나요?!

2023-11-05 19:47 UTC, hyoribogo commented on src/utils/constants.ts
> +  NAME_MAX_LENGTH: 12,
이름이 2글자인 사람은 어떡하나요?!

2023-11-07 04:31 UTC, merged