Rev 70/아이콘 버튼 컴포넌트
prgrms-web-devcourse/Team-12-ReviewRanger-FE pull request #8
Opened 2023-10-30 03:07 UTC by khj0426

## 📑 구현 내용 

아이콘이 있는 버튼 컴포넌트를 개발했습니다.!
뭔가 이 컴포넌트가 쓰이는 곳이 많을 것 같아서 여러 가지를 고려해서 만들어보았어요!.!
`Ripple UI`에서 기본적으로 여러 색상 변수를 제공해줘서 (아래 사진처럼) 이 색상 변수를 `Props`로 사용할 수 있게 설정했어요!

```ts
//색상과 배경색, 크기, disabled여부를 받습니다
interface IconButtonProps {
  color?:
    | 'red'
    | 'blue'
    | 'green'
    | 'yellow'
    | 'pink'
    | 'purple'
    | 'gray'
    | 'slate'
    | 'primary'
    | 'secondary'
    | 'error'
    | 'success'
    | 'warning'
  background?:
    | 'red'
    | 'blue'
    | 'green'
    | 'yellow'
    | 'pink'
    | 'purple'
    | 'gray'
    | 'slate'
    | 'primary'
    | 'secondary'
    | 'error'
    | 'success'
    | 'warning'
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  loading?: boolean
  disabled?: boolean
}

```

기본적으로는 아래의 형태이지만 필요에 따라 다른 색상을 쓰고 싶다면 `Props`로 색상을 넘기면 됩니다!

![image](https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-FE/assets/59411107/e09d12c3-0a67-4c9a-86f3-695623079932)

disabled처리된 경우
![image](https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-FE/assets/59411107/ced942a6-13d9-42b6-91ec-e362cb007bd1)

로딩중일 떄
![image](https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-FE/assets/59411107/c37fd466-5730-441d-acdb-9329da0d3885)

사용하는 곳에서는 `children`으로 아이콘을 넘기면 되는데, 이 방식이 적절한 지는..잘 모르겠어요.!..

```tsx
import { TableSend } from '@/assets/icons'
import IconButton from '@/components'

function App() {
  return (
    <>
      <IconButton>
        <TableSend />
      </IconButton>
    </>
  )
}

export default App

```

<br/>

## 🚧 참고 사항

https://www.ripple-ui.com/docs/get-started/theme
https://github.com/Siumauricio/rippleui/blob/main/components/inputs/button.css
<br/>

- 보통 아이콘이 있는 버튼을 만들 때 아이콘을 어떻게 넘기나요..? 저는 children으로 넘기는 방법밖에 생각이 안났어요..!
- 디자인이 더 구체화되면 theme을 만들어서 쓰는 것도 좋을 거 같습니다.!

2023-10-30 11:21 UTC, hayamaster reviewed
고생하셨습니다 효중님!! 확인했습니다!

2023-10-30 11:21 UTC, hayamaster commented on src/utils/generateClass.ts
> +}
generateClass의 용도가 배열로 오는 class 값들을 하나의 문자열로 합치는 과정인 듯 합니다만, 혹시 왜 필요한 것일까요??
그냥 하나의 문자열을 prop으로 넘겨주면 안될까요?!

2023-10-30 11:21 UTC, hayamaster commented on src/components/IconButton/IconButton.tsx
> +      {!loading && children}
loading을 prop으로 받는 이유가 궁금합니다! loading 중일 때는, children인 Icon을 안보여주는 것 일까요?

2023-10-30 11:21 UTC, hayamaster commented on src/components/IconButton/IconButton.tsx
> +      Default
이 Default는 무조건 보여지는 것 같습니다! 사용자가 Button text도 지정해주면 좋을 것 같습니다!

2023-10-31 01:26 UTC, hyoribogo requested changes
> 보통 아이콘이 있는 버튼을 만들 때 아이콘을 어떻게 넘기나요..? 저는 children으로 넘기는 방법밖에 생각이 안났어요..!
1. `icon: string | JSX.Element` 로 넘겨주는 방법
2. 효중님처럼 `children`으로 넘겨주는 방법

저는 지금처럼 구현해도 괜찮을 것 같아요!  아마 버튼에 gap 속성이 추가되면 좋을 것 같네요!

2023-10-31 01:26 UTC, hyoribogo commented on src/components/IconButton/IconButton.css
나중에 tatilwind.config.js에 지정해주면 좋을 것 같아요!

2023-10-31 01:26 UTC, hyoribogo commented on src/components/IconButton/IconButton.tsx
> +      {!loading && children}
저도 궁금합니다!

2023-10-31 01:26 UTC, hyoribogo commented on src/utils/generateClass.ts
> +}
저도 이 부분이 불필요하다고 생각이 들었어요!

2023-10-31 03:37 UTC, khj0426 commented on src/utils/generateClass.ts
> +}
지워두겠습니다!!

2023-10-31 03:38 UTC, khj0426 commented on src/components/IconButton/IconButton.tsx
> +      {!loading && children}
사실 불필요한 prop인거 같아서 제거를 하는 게 좋을 거 같아요!!

2023-10-31 03:38 UTC, khj0426 commented on src/components/IconButton/IconButton.tsx
> +      Default
오 감사합니다!!!

2023-10-31 03:38 UTC, khj0426 commented on src/components/IconButton/IconButton.css
좋습니다!!

2023-10-31 06:23 UTC, hyoribogo approved these changes

2023-10-31 06:23 UTC, merged